trigger:
- main
pr:
- '*'

pool:
  name: Default

variables:
  app_location: '/'
  output_location: 'dist'

steps:
- checkout: self

- task: UseNode@1
  displayName: Use Node 22.12.0
  inputs:
    version: '22.12.0'

- script: |
    node -v
    npm -v
  displayName: Show Node & npm versions

- task: Cache@2
  displayName: Cache npm
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    path: $(Pipeline.Workspace)/.npm
    restoreKeys: |
      npm | "$(Agent.OS)"
      npm

- script: |
    set -e
    [ -n "${AZURE_STATIC_WEB_APPS_API_TOKEN:-}" ] || { echo "Missing AZURE_STATIC_WEB_APPS_API_TOKEN"; exit 1; }
  displayName: Check secrets present
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  env:
    AZURE_STATIC_WEB_APPS_API_TOKEN: $(AZURE_STATIC_WEB_APPS_API_TOKEN)

- script: |
    set -e
    npm config set cache "$(Pipeline.Workspace)/.npm" --global
    npm ci
    npm run build
  displayName: Build SPA
  env:
    VITE_API_BASE_URL: $(VITE_API_BASE_URL)

# ---- Production deploy (main branch) ----
- task: AzureStaticWebApp@0
  displayName: Deploy to SWA (production)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
    app_location: $(app_location)
    output_location: $(output_location)
    deployment_environment: 'production'
