trigger:
- main

pool:
  name: Default

variables:
  appName: react-hello
  appPort: '8080'
  imageTag: $(Build.BuildId)

steps:
- checkout: self

- script: |
    set -e
    echo "Building Docker image..."
    docker build --progress=plain -t $(appName):$(imageTag) .
  displayName: Build Docker image

- script: |
    set -e
    echo "Stopping old container (if any)..."
    docker rm -f $(appName) || true

    echo "Starting new container..."
    docker run -d --name $(appName) \
      -p $(appPort):80 \
      --restart unless-stopped \
      $(appName):$(imageTag)

    echo "Health check..."
    (curl -fsS http://localhost:$(appPort) || wget -qO- http://localhost:$(appPort)) | head -n1

    echo "ps:"
    docker ps --filter name=$(appName)
  displayName: Run container and health check
