# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

variables:
  appName: react-hello
  appPort: '8080'
  imageTag: $(Build.BuildId)

steps:
- checkout: self

# Build the docker image on the agent
- script: |
    echo "Build Docker image..."
    docker build -t $(appName):$(imageTag) .
  displayName: Build Docker image

- script: |
    echo "Stopping ald container (if any)..."
    docker rm -f $(appName) || true
    
    echo "Starting new container..."
    docker run -d --name $(appName) \
      -p $(appPort):80 \
      --restart unless-stopped \
      $(appName):$(Build.Build)

    echo "Health check..."
    (curl -fsS http://localhost:$(appPort) || wget -qO- http://localhost:$(appPort) | head -n1

    echo "ps:"
    docker ps --filter name=$(appName)
  displayName: Run container and health check
